/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package testsfor1899

import org.junit.Test
class LibraryTest {


    @Test
    void test() {
        assert Thread.currentThread().getContextClassLoader().getResource("somefolder/ok.any") != null
        assert Thread.currentThread().getContextClassLoader().getResource("somefolder/failed.log") != null
    }

}
